### PR TITLE
Performance improvement when using multiple instances

### PR DESCRIPTION
**Pull request by Toflar**
Hi there, excellent library, love it! ❤️ 

I noticed that when you instantiate the `LanguageDetector` multiple times, you end up with a memory leak.
Can be easily reproduced:

```php
<?php

use Nitotm\Eld\LanguageDetector;

require_once 'vendor/autoload.php';

$startTime = microtime(true);
$detectors = [];

for ($i = 0; $i < 20; $i++) {
    $detectors[] = new LanguageDetector();
}

echo 'Memory usage: '.round(memory_get_usage() / 1024 / 1024, 2).'MiB (peak: '.round(memory_get_peak_usage() / 1024 / 1024, 2).'MiB), time: '.round(microtime(true) - $startTime, 2).'s';
```

Current main:

```
Memory usage: 958.19MiB (peak: 990.14MiB), time: 0.96s
```

After the PR:

```
Memory usage: 48.93MiB (peak: 80.8MiB), time: 0.05s
```

There are probably other ways to solve the issue but that was the quickfix :-)

### CODE REVIEW

**Comment by nitotm** [comment]
Most of the time I use the web server (php-cgi), where this error does not reproduce, I'm guessing because of OPcache.

Anyways, this is just something I noticed, the code should not rely on any php cache, so you fix is good.

I will make sure I test things like this with non cgi.

**Comment by Toflar** [comment]
Yeah usually people won't use multiple instances of the `LanguageDetector` anyway I guess but still, it's something that should be fixed :)

**Comment by Toflar** [comment]
You've destroyed the whole point of this PR in your commit in https://github.com/nitotm/efficient-language-detector/commit/58b8a7e5915bbad5d4fa243c07496b400f325869 again because now it's not a static array anymore. Meaning that when you instantiate multiple `LanguageDetector` instances, it will again become slow.

**Comment by nitotm** [comment]
> You've destroyed the whole point of this PR in your commit in [58b8a7e](https://github.com/nitotm/efficient-language-detector/commit/58b8a7e5915bbad5d4fa243c07496b400f325869) again because now it's not a static array anymore. Meaning that when you instantiate multiple `LanguageDetector` instances, it will again become slow.

Hi, I'm looking at the code, and I am not seeing what you mean.
I see it is still static, I made tests and it works as expected. 

You may have missed it, but your `private static  array $fileContents = [];` was on line 32, with bad format (double space), and now it is on line 19

The commit you are referencing it is a reformat, plus only one change, that is using `require` instead of `require_once`:
The reason of using `require`, is because the `if` condition will already prevent the same file to be loaded twice, and in the event there is an error, which I cannot foresee what could be, I thought it rather loads the file than fatally fail.

I reasoned it a little more, whether to use `require`, but since it is not the topic of your message I will not dwell on it. In any case, if you think that is a problem, I am open to reconsidering it.

**Pull request merged**
